global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "product-service"
    metrics_path: "/product/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Product Service Application'
  - job_name: "order-service"
    metrics_path: "/order/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Order Service Application'
  - job_name: "inventory-service"
    metrics_path: "/inventory/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Inventory Service Application'
  - job_name: "notification-service"
    metrics_path: "/notification/actuator/prometheus"
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Notification Service Application'